<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Daví Barbosa Pereira de Sousa">
<meta name="author" content="Marcela Silva de Araújo">

<title>Módulo 2: Geoestatística para dados não normais</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="QMD_Modulo2_files/libs/clipboard/clipboard.min.js"></script>
<script src="QMD_Modulo2_files/libs/quarto-html/quarto.js"></script>
<script src="QMD_Modulo2_files/libs/quarto-html/popper.min.js"></script>
<script src="QMD_Modulo2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="QMD_Modulo2_files/libs/quarto-html/anchor.min.js"></script>
<link href="QMD_Modulo2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="QMD_Modulo2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="QMD_Modulo2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="QMD_Modulo2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="QMD_Modulo2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar zindex-bottom">
</div>
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Módulo 2: Geoestatística para dados não normais</h1>
</div>


<div class="quarto-title-meta-author">
  <div class="quarto-title-meta-heading">Authors</div>
  <div class="quarto-title-meta-heading">Affiliation</div>
  
    <div class="quarto-title-meta-contents">
    <p class="author">Daví Barbosa Pereira de Sousa </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universidade Federal de Lavras
          </p>
      </div>
    <div class="quarto-title-meta-contents">
    <p class="author">Marcela Silva de Araújo </p>
  </div>
  <div class="quarto-title-meta-contents">
        <p class="affiliation">
            Universidade Federal de Lavras
          </p>
      </div>
  </div>

<div class="quarto-title-meta">

      
  
    
  </div>
  


</header>


<section id="pacotes" class="level2">
<h2 class="anchored" data-anchor-id="pacotes">Pacotes</h2>
<p>Leitura dos pacotes necessário para executar as etapas de manipulação, análise geoestatística, ajuste de modelos e visualização.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(readr)        <span class="co"># Leitura da base de dados</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geoR)         <span class="co"># Análise geoestatística</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geobr)        <span class="co"># Obtenção de shapefiles do IBGE</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)        <span class="co"># Manipulação de dados</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)           <span class="co"># Manipulação de dados espaciais</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggplot2)      <span class="co"># Criação de gráficos</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="leitura-dos-dados" class="level2">
<h2 class="anchored" data-anchor-id="leitura-dos-dados">Leitura dos dados</h2>
<p>Importamos a base de dados original e avaliamos suas características iniciais por meio de estatísticas descritivas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>df_airbnb <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">"listings.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(df_airbnb)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 42,013
Columns: 18
$ id                             &lt;dbl&gt; 2302715, 2304688, 2306547, 2306767, 230…
$ name                           &lt;chr&gt; "guilherme", "OLIMPÍADAS 2016", "Amplo …
$ host_id                        &lt;int&gt; 11706874, 10405816, 4107346, 11386725, …
$ host_name                      &lt;chr&gt; "Guilherme", "Eurico", "Vera Lucia", "C…
$ neighbourhood_group            &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…
$ neighbourhood                  &lt;chr&gt; "Anil", "Ipanema", "Copacabana", "Copac…
$ latitude                       &lt;dbl&gt; -22.95221, -22.98767, -22.97333, -22.96…
$ longitude                      &lt;dbl&gt; -43.32944, -43.18991, -43.18857, -43.17…
$ room_type                      &lt;chr&gt; "Entire home/apt", "Entire home/apt", "…
$ price                          &lt;int&gt; 2700, 837, 800, 190, 220, 401, 219, 399…
$ minimum_nights                 &lt;int&gt; 10, 7, 5, 3, 2, 2, 7, 3, 3, 7, 3, 1, 5,…
$ number_of_reviews              &lt;int&gt; 0, 0, 13, 193, 28, 36, 58, 38, 28, 3, 5…
$ last_review                    &lt;chr&gt; "", "", "2025-03-05", "2025-03-03", "20…
$ reviews_per_month              &lt;dbl&gt; NA, NA, 0.21, 1.44, 0.21, 0.48, 0.52, 0…
$ calculated_host_listings_count &lt;int&gt; 1, 1, 1, 6, 1, 4, 12, 1, 1, 1, 1, 1, 2,…
$ availability_365               &lt;int&gt; 365, 365, 257, 66, 242, 8, 205, 107, 31…
$ number_of_reviews_ltm          &lt;int&gt; 0, 0, 3, 19, 4, 8, 10, 11, 3, 0, 5, 0, …
$ license                        &lt;lgl&gt; NA, NA, NA, NA, NA, NA, NA, NA, NA, NA,…</code></pre>
</div>
</div>
</section>
<section id="filtros-e-limpeza" class="level2">
<h2 class="anchored" data-anchor-id="filtros-e-limpeza">Filtros e limpeza</h2>
<p>Convertimos a variável de data para o formato adequado e aplicamos filtros para manter apenas observações relevantes ao estudo. Selecionamos imóveis avaliados a partir de 2025, com preço até R$500 e mantemos apenas um imóvel por coordenada (o de menor valor), evitando duplicidade espacial.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a>df_airbnb<span class="sc">$</span>last_review <span class="ot">&lt;-</span> <span class="fu">as.Date</span>(df_airbnb<span class="sc">$</span>last_review)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>df_airbnb_2025 <span class="ot">&lt;-</span> df_airbnb <span class="sc">|&gt;</span> </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(last_review <span class="sc">&gt;=</span> <span class="st">"2025-01-01"</span>) <span class="sc">|&gt;</span>  <span class="co"># Filtrar avaliações de 2025</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(price)) <span class="sc">|&gt;</span>                <span class="co"># Remover preços NA</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(price <span class="sc">&lt;=</span><span class="dv">500</span>)  <span class="sc">|&gt;</span>                 <span class="co"># Remover preços superiores a 500</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(latitude, longitude) <span class="sc">|&gt;</span>        <span class="co"># Agrupar por coordenadas</span></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">slice_min</span>(price, <span class="at">with_ties =</span> <span class="cn">FALSE</span>) <span class="sc">|&gt;</span>  <span class="co"># Manter o de menor preço</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ungroup</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Avaliamos as estatísticas resumo após os filtros aplicados.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(df_airbnb_2025)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       id                name              host_id           host_name        
 Min.   :1.788e+04   Length:16399       Min.   :     3607   Length:16399      
 1st Qu.:4.778e+07   Class :character   1st Qu.: 35534219   Class :character  
 Median :9.495e+17   Mode  :character   Median :156710364   Mode  :character  
 Mean   :7.429e+17                      Mean   :224926404                     
 3rd Qu.:1.233e+18                      3rd Qu.:408071697                     
 Max.   :1.379e+18                      Max.   :683718376                     
 neighbourhood_group neighbourhood         latitude        longitude     
 Mode:logical        Length:16399       Min.   :-23.07   Min.   :-43.70  
 NA's:16399          Class :character   1st Qu.:-22.98   1st Qu.:-43.23  
                     Mode  :character   Median :-22.97   Median :-43.19  
                                        Mean   :-22.96   Mean   :-43.24  
                                        3rd Qu.:-22.94   3rd Qu.:-43.18  
                                        Max.   :-22.75   Max.   :-43.11  
  room_type             price       minimum_nights    number_of_reviews
 Length:16399       Min.   : 44.0   Min.   :  1.000   Min.   :  1.00   
 Class :character   1st Qu.:180.0   1st Qu.:  1.000   1st Qu.:  5.00   
 Mode  :character   Median :252.0   Median :  2.000   Median : 17.00   
                    Mean   :265.9   Mean   :  2.535   Mean   : 39.15   
                    3rd Qu.:346.0   3rd Qu.:  3.000   3rd Qu.: 49.00   
                    Max.   :500.0   Max.   :365.000   Max.   :726.00   
  last_review         reviews_per_month calculated_host_listings_count
 Min.   :2025-01-01   Min.   : 0.020    Min.   :  1.000               
 1st Qu.:2025-02-24   1st Qu.: 0.670    1st Qu.:  1.000               
 Median :2025-03-05   Median : 1.190    Median :  2.000               
 Mean   :2025-02-26   Mean   : 1.609    Mean   :  9.224               
 3rd Qu.:2025-03-10   3rd Qu.: 2.200    3rd Qu.:  5.000               
 Max.   :2025-03-20   Max.   :13.650    Max.   :214.000               
 availability_365 number_of_reviews_ltm license       
 Min.   :  0.0    Min.   :  1.00        Mode:logical  
 1st Qu.: 77.0    1st Qu.:  3.00        NA's:16399    
 Median :159.0    Median :  9.00                      
 Mean   :179.2    Mean   : 13.56                      
 3rd Qu.:287.0    3rd Qu.: 20.00                      
 Max.   :365.0    Max.   :138.00                      </code></pre>
</div>
</div>
<p>Visualizamos a distribuição dos preços para investigar assimetria e possíveis valores extremos.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(df_airbnb_2025<span class="sc">$</span>price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/boxplot%201-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="amostra" class="level2">
<h2 class="anchored" data-anchor-id="amostra">Amostra</h2>
<p>Para reduzir custo computacional, selecionamos uma amostra aleatória de 1.000 observações. Fixamos uma semente para garantir reprodutibilidade.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>)</span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>amostra <span class="ot">&lt;-</span> <span class="fu">sample_n</span>(df_airbnb_2025, <span class="dv">1000</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Verificamos novamente a distribuição da variável resposta na amostra.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(amostra<span class="sc">$</span>price)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/boxplot%202-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="estruturação-geoestatística-dos-dados" class="level2">
<h2 class="anchored" data-anchor-id="estruturação-geoestatística-dos-dados">Estruturação geoestatística dos dados</h2>
<p>Transformamos o conjunto amostral no objeto geoespacial utilizado pelo <code>geoR</code>, definindo coordenadas e variável resposta. Em seguida, avaliamos o resumo dos dados e testamos a hipótese de normalidade.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>airbnb <span class="ot">&lt;-</span> <span class="fu">as.geodata</span>(amostra, <span class="at">coords.col =</span> <span class="fu">c</span>(<span class="dv">8</span>,<span class="dv">7</span>), <span class="at">data.col =</span> <span class="dv">10</span>)</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(airbnb)        <span class="co"># Exibe um resumo dos dados</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Number of data points: 1000 

Coordinates summary
    longitude  latitude
min -43.64404 -23.06393
max -43.10577 -22.75086

Distance summary
         min          max 
2.225593e-06 5.740489e-01 

Data summary
   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  54.00  175.00  250.00  262.77  343.25  500.00 </code></pre>
</div>
</div>
<p>As coordenadas geográficas indicam que os imóveis estão distribuídos aproximadamente entre as longitudes -43,64 e -43,10 e latitudes -23,06 e -22,75, cobrindo uma faixa espacial coerente com a área urbana da cidade. As distâncias entre pontos variam de praticamente zero até cerca de 0,57 graus, sugerindo presença de imóveis bastante próximos entre si, o que é relevante para análise de dependência espacial. Quanto aos valores, os preços variam de R$ 54 a R$ 500, com mediana de R$ 250 e média de R$ 262,77, indicando leve assimetria à direita, isto é, presença de imóveis com preços mais elevados puxando a média para cima.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(airbnb)  <span class="co"># Plota os dados</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/unnamed-chunk-1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>Primeiro, no painel espacial (canto superior esquerdo), vemos que os imóveis não estão distribuídos aleatoriamente: há concentração clara em uma faixa longitudinal específica, sugerindo agrupamento espacial, exatamente o tipo de padrão que justifica o uso de geoestatística. Pontos muito próximos indicam potencial autocorrelação espacial, ou seja, valores de diárias tendem a se parecer com os valores de imóveis vizinhos.</p></li>
<li><p>Segundo, os diagramas de dispersão entre coordenadas e preços mostram que não há uma relação linear simples entre localização (X ou Y) e valor, mas há indícios de estrutura: em certas faixas de longitude há maior concentração de preços elevados. Isso sugere tendência espacial, que pode precisar ser modelada antes do cálculo do variograma.</p></li>
<li><p>Por fim, o histograma indica distribuição assimétrica à direita, com maior concentração entre aproximadamente R$150 e R$350 e cauda superior estendendo-se até R$500. A média maior que a mediana já antecipava isso.</p></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="fu">shapiro.test</span>(airbnb<span class="sc">$</span>data)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Shapiro-Wilk normality test

data:  airbnb$data
W = 0.96758, p-value = 3.912e-14</code></pre>
</div>
</div>
<p>Os preços apresentam desvio significativo da normalidade segundo o teste de Shapiro–Wilk (p &lt; 0,001).</p>
</section>
<section id="semivariograma-empírico" class="level2">
<h2 class="anchored" data-anchor-id="semivariograma-empírico">Semivariograma empírico</h2>
<p>Calculamos o semivariograma utilizando o estimador clássico e analisamos a dispersão dentro das classes de distância.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>varioA<span class="ot">&lt;-</span><span class="fu">variog</span>(airbnb, <span class="at">bin.cloud=</span>T, <span class="at">estimator.type=</span><span class="st">"classical"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variog: computing omnidirectional variogram</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(varioA<span class="sc">$</span>bin.cloud, <span class="at">xlab=</span><span class="st">"Numero da Classe de distâncias"</span>, <span class="at">ylab=</span><span class="st">"Diferenças ao quadrado"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/semivariograma%20classico-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O boxplot da nuvem de variograma mostra que nas primeiras classes (distâncias menores), as diferenças ao quadrado tendem a ser menores e menos dispersas. Conforme a distância aumenta, a variabilidade cresce e a dispersão dentro das classes também aumenta. Isso sugere dependência espacial: imóveis próximos tendem a ter preços mais semelhantes, enquanto imóveis mais distantes apresentam maior discrepância de valores.</p>
<p>Note também a presença de muitos <em>outliers</em> em praticamente todas as classes. Isso é coerente com a assimetria já observada na distribuição dos preços. Valores muito altos (ou muito baixos) ampliam as diferenças ao quadrado, inflando a dispersão. Em termos práticos, isso pode afetar o ajuste do modelo teórico do variograma.</p>
<p>Repetimos o cálculo utilizando o estimador robusto de Cressie-Hawkins (modulus), mais apropriado para dados não normais ou com presença de <em>outliers</em>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a>varioB<span class="ot">&lt;-</span><span class="fu">variog</span>(airbnb, <span class="at">bin.cloud=</span>T, <span class="at">estimator.type=</span><span class="st">"modulus"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variog: computing omnidirectional variogram</code></pre>
</div>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">boxplot</span>(varioB<span class="sc">$</span>bin.cloud, <span class="at">xlab=</span><span class="st">"Numero da Classe de distâncias"</span>, <span class="at">ylab=</span><span class="st">"Diferenças ao quadrado"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/semivariograma%20robusto-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O uso do estimador robusto de Cressie–Hawkins reduziu a influência de outliers presentes na distribuição dos preços, produzindo um padrão de variabilidade espacial mais estável e consistente. A estrutura de dependência espacial permanece evidente, porém com menor dispersão intra-classe.</p>
<p>Construímos o semivariograma binned utilizando o estimador robusto.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a>vc<span class="ot">=</span><span class="fu">variog</span>(airbnb, <span class="at">option=</span><span class="st">"bin"</span>, <span class="at">estimator.type=</span><span class="st">"modulus"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variog: computing omnidirectional variogram</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vc)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/semivariograma%20bin-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Analisamos possíveis direcionalidades [(an)isotropia] por meio do variograma em quatro direções.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>v4<span class="ot">=</span><span class="fu">variog4</span>(airbnb, <span class="at">option=</span><span class="st">"bin"</span>,</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>           <span class="at">estimator.type=</span><span class="st">"modulus"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variog: computing variogram for direction = 0 degrees (0 radians)
        tolerance angle = 22.5 degrees (0.393 radians)
variog: computing variogram for direction = 45 degrees (0.785 radians)
        tolerance angle = 22.5 degrees (0.393 radians)
variog: computing variogram for direction = 90 degrees (1.571 radians)
        tolerance angle = 22.5 degrees (0.393 radians)
variog: computing variogram for direction = 135 degrees (2.356 radians)
        tolerance angle = 22.5 degrees (0.393 radians)
variog: computing omnidirectional variogram</code></pre>
</div>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(v4)</span>
<span id="cb26-2"><a href="#cb26-2" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(vc, <span class="at">type=</span><span class="st">"l"</span>, <span class="at">lwd=</span><span class="dv">3</span>, <span class="at">col=</span><span class="st">"red"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/semivariograma%204%20direçoes-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Sem nenhum problema, aparenta estar isotrópico, então, limitamos a distância máxima para focar na região onde há estrutura espacial mais relevante. Neste caso, consideramos a distância de até 90 metros (0,09km).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>semi <span class="ot">&lt;-</span> <span class="fu">variog</span>(airbnb, <span class="at">max.dist =</span> <span class="fl">0.09</span>, </span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a>               <span class="at">option=</span><span class="st">"bin"</span>, <span class="at">estimator.type=</span><span class="st">"modulus"</span>);semi</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variog: computing omnidirectional variogram</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>$u
 [1] 0.003461511 0.010384533 0.017307555 0.024230577 0.031153599 0.038076622
 [7] 0.044999644 0.051922666 0.058845688 0.065768710 0.072691732 0.079614754
[13] 0.086537776

$v
 [1]  9677.934  9862.176  9982.055 11312.038 12138.852 11727.985 12067.775
 [8] 13823.215 15217.996 16515.606 18340.421 20116.031 17796.500

$n
 [1] 30593 36962 35373 30819 26551 20672 19908 23951 21854 21821 19033 13117
[13]  8031

$sd
 [1] 4.141344 4.150606 4.171453 4.249406 4.288297 4.317260 4.332413 4.378781
 [9] 4.406929 4.455189 4.498013 4.571296 4.534722

$bins.lim
 [1] 1.000000e-12 6.923022e-03 1.384604e-02 2.076907e-02 2.769209e-02
 [6] 3.461511e-02 4.153813e-02 4.846115e-02 5.538418e-02 6.230720e-02
[11] 6.923022e-02 7.615324e-02 8.307627e-02 8.999929e-02

$ind.bin
 [1] TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE TRUE

$var.mark
[1] 12436.38

$beta.ols
[1] 262.77

$output.type
[1] "bin"

$max.dist
[1] 0.09

$estimator.type
[1] "modulus"

$n.data
[1] 1000

$lambda
[1] 1

$trend
[1] "cte"

$pairs.min
[1] 2

$nugget.tolerance
[1] 1e-12

$direction
[1] "omnidirectional"

$tolerance
[1] "none"

$uvec
 [1] 0.003461511 0.010384533 0.017307555 0.024230577 0.031153599 0.038076622
 [7] 0.044999644 0.051922666 0.058845688 0.065768710 0.072691732 0.079614754
[13] 0.086537776

$call
variog(geodata = airbnb, option = "bin", estimator.type = "modulus", 
    max.dist = 0.09)

attr(,"class")
[1] "variogram"</code></pre>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(semi)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/semivariograma%2080m-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O variograma ajustado indica dependência espacial na variável analisada, com patamar estimado em 20.000, alcance de 0,08 e efeito pepita de 10.000. Isso significa que a semivariância cresce com a distância até aproximadamente 0,08 unidades, ponto a partir do qual a dependência espacial praticamente desaparece. O valor relativamente elevado da pepita sugere que há considerável variabilidade em pequenas escalas, enquanto a diferença entre o patamar total e a pepita indica que cerca de metade da variabilidade é explicada por estrutura espacial. Em termos práticos, há influência do efeito locacional até o alcance estimado, mas também uma parcela importante de variação que não é explicada apenas pela proximidade espacial.</p>
</section>
<section id="ajuste-de-modelos-teóricos" class="level2">
<h2 class="anchored" data-anchor-id="ajuste-de-modelos-teóricos">Ajuste de modelos teóricos</h2>
<p>Ajustamos diferentes modelos teóricos de semivariograma por mínimos quadrados ponderados (Cressie), com os mesmos valores iniciais, para posterior comparação de desempenho.</p>
<p>As informações utilizadas foram tiradas do semivariograma anterior, do qual sigma2 (patamar) = 20.000, phi (alcance) = 0,08 e tau2 (pepita) = 10.000.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar modelo: matern</span></span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>modelo_matern <span class="ot">&lt;-</span> <span class="fu">variofit</span>(semi,</span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">cov.model =</span> <span class="st">"matern"</span>,</span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">ini.cov.pars =</span> <span class="fu">c</span>(<span class="dv">20000</span>, <span class="fl">0.08</span>),</span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">nugget =</span><span class="dv">10000</span>, <span class="at">wei=</span><span class="st">"cressie"</span>,</span>
<span id="cb31-6"><a href="#cb31-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">min=</span><span class="st">"optim"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variofit: covariance model used is matern 
variofit: weights used: cressie 
variofit: minimisation function used: optim </code></pre>
</div>
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar modelo: exponential</span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>modelo_exponential <span class="ot">&lt;-</span> <span class="fu">variofit</span>(semi,</span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>                               <span class="at">cov.model =</span> <span class="st">"exponential"</span>,</span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>                               <span class="at">ini.cov.pars =</span> <span class="fu">c</span>(<span class="dv">20000</span>, <span class="fl">0.08</span>),</span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>                               <span class="at">nugget =</span><span class="dv">10000</span>, <span class="at">wei=</span><span class="st">"cressie"</span>,</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>                               <span class="at">min=</span><span class="st">"optim"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variofit: covariance model used is exponential 
variofit: weights used: cressie 
variofit: minimisation function used: optim </code></pre>
</div>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar modelo: gaussian</span></span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>modelo_gaussian <span class="ot">&lt;-</span> <span class="fu">variofit</span>(semi,</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">cov.model =</span> <span class="st">"gaussian"</span>,</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ini.cov.pars =</span> <span class="fu">c</span>(<span class="dv">20000</span>, <span class="fl">0.08</span>),</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">nugget =</span><span class="dv">10000</span>, <span class="at">wei=</span><span class="st">"cressie"</span>,</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">min=</span><span class="st">"optim"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variofit: covariance model used is gaussian 
variofit: weights used: cressie 
variofit: minimisation function used: optim </code></pre>
</div>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar modelo: spherical</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>modelo_spherical <span class="ot">&lt;-</span> <span class="fu">variofit</span>(semi,</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a>                             <span class="at">cov.model =</span> <span class="st">"spherical"</span>,</span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>                             <span class="at">ini.cov.pars =</span> <span class="fu">c</span>(<span class="dv">20000</span>, <span class="fl">0.08</span>),</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>                             <span class="at">nugget =</span><span class="dv">10000</span>, <span class="at">wei=</span><span class="st">"cressie"</span>,</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>                             <span class="at">min=</span><span class="st">"optim"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variofit: covariance model used is spherical 
variofit: weights used: cressie 
variofit: minimisation function used: optim </code></pre>
</div>
<div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar modelo: circular</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>modelo_circular <span class="ot">&lt;-</span> <span class="fu">variofit</span>(semi,</span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">cov.model =</span> <span class="st">"circular"</span>,</span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ini.cov.pars =</span> <span class="fu">c</span>(<span class="dv">20000</span>, <span class="fl">0.08</span>),</span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">nugget =</span><span class="dv">10000</span>, <span class="at">wei=</span><span class="st">"cressie"</span>,</span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">min=</span><span class="st">"optim"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variofit: covariance model used is circular 
variofit: weights used: cressie 
variofit: minimisation function used: optim </code></pre>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar modelo: cubic</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>modelo_cubic <span class="ot">&lt;-</span> <span class="fu">variofit</span>(semi,</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>                         <span class="at">cov.model =</span> <span class="st">"cubic"</span>,</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a>                         <span class="at">ini.cov.pars =</span> <span class="fu">c</span>(<span class="dv">20000</span>, <span class="fl">0.08</span>),</span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>                         <span class="at">nugget =</span><span class="dv">10000</span>, <span class="at">wei=</span><span class="st">"cressie"</span>,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>                         <span class="at">min=</span><span class="st">"optim"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variofit: covariance model used is cubic 
variofit: weights used: cressie 
variofit: minimisation function used: optim </code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar modelo: wave</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a>modelo_wave <span class="ot">&lt;-</span> <span class="fu">variofit</span>(semi,</span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">cov.model =</span> <span class="st">"wave"</span>,</span>
<span id="cb43-4"><a href="#cb43-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">ini.cov.pars =</span> <span class="fu">c</span>(<span class="dv">20000</span>, <span class="fl">0.08</span>),</span>
<span id="cb43-5"><a href="#cb43-5" aria-hidden="true" tabindex="-1"></a>                        <span class="at">nugget =</span><span class="dv">10000</span>, <span class="at">wei=</span><span class="st">"cressie"</span>,</span>
<span id="cb43-6"><a href="#cb43-6" aria-hidden="true" tabindex="-1"></a>                        <span class="at">min=</span><span class="st">"optim"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variofit: covariance model used is wave 
variofit: weights used: cressie 
variofit: minimisation function used: optim </code></pre>
</div>
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar modelo: powered.exponential</span></span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>modelo_powered <span class="ot">&lt;-</span> <span class="fu">variofit</span>(semi,</span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>                           <span class="at">cov.model =</span> <span class="st">"powered.exponential"</span>,</span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>                           <span class="at">ini.cov.pars =</span> <span class="fu">c</span>(<span class="dv">20000</span>, <span class="fl">0.08</span>),</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a>                           <span class="at">nugget =</span><span class="dv">10000</span>, <span class="at">wei=</span><span class="st">"cressie"</span>,</span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a>                           <span class="at">min=</span><span class="st">"optim"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variofit: covariance model used is powered.exponential 
variofit: weights used: cressie 
variofit: minimisation function used: optim </code></pre>
</div>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar modelo: cauchy</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>modelo_cauchy <span class="ot">&lt;-</span> <span class="fu">variofit</span>(semi,</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a>                          <span class="at">cov.model =</span> <span class="st">"cauchy"</span>,</span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a>                          <span class="at">ini.cov.pars =</span> <span class="fu">c</span>(<span class="dv">20000</span>, <span class="fl">0.08</span>),</span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>                          <span class="at">nugget =</span><span class="dv">10000</span>, <span class="at">wei=</span><span class="st">"cressie"</span>,</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>                          <span class="at">min=</span><span class="st">"optim"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variofit: covariance model used is cauchy 
variofit: weights used: cressie 
variofit: minimisation function used: optim </code></pre>
</div>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Ajustar modelo: gneiting</span></span>
<span id="cb49-2"><a href="#cb49-2" aria-hidden="true" tabindex="-1"></a>modelo_gneiting <span class="ot">&lt;-</span> <span class="fu">variofit</span>(semi,</span>
<span id="cb49-3"><a href="#cb49-3" aria-hidden="true" tabindex="-1"></a>                            <span class="at">cov.model =</span> <span class="st">"gneiting"</span>,</span>
<span id="cb49-4"><a href="#cb49-4" aria-hidden="true" tabindex="-1"></a>                            <span class="at">ini.cov.pars =</span> <span class="fu">c</span>(<span class="dv">20000</span>, <span class="fl">0.08</span>),</span>
<span id="cb49-5"><a href="#cb49-5" aria-hidden="true" tabindex="-1"></a>                            <span class="at">nugget =</span><span class="dv">10000</span>, <span class="at">wei=</span><span class="st">"cressie"</span>,</span>
<span id="cb49-6"><a href="#cb49-6" aria-hidden="true" tabindex="-1"></a>                            <span class="at">min=</span><span class="st">"optim"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>variofit: covariance model used is gneiting 
variofit: weights used: cressie 
variofit: minimisation function used: optim </code></pre>
</div>
</div>
<p>Plotamos o semivariograma experimental juntamente com todos os modelos ajustados para comparação visual.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Plot do semivariograma experimental</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(semi, </span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>, </span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"blue"</span>, </span>
<span id="cb51-5"><a href="#cb51-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Distância (km)"</span>, </span>
<span id="cb51-6"><a href="#cb51-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Semivariância"</span>)</span>
<span id="cb51-7"><a href="#cb51-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-8"><a href="#cb51-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Adiciona cada modelo com uma cor diferente</span></span>
<span id="cb51-9"><a href="#cb51-9" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(modelo_matern, <span class="at">col =</span> <span class="st">"red"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb51-10"><a href="#cb51-10" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(modelo_exponential, <span class="at">col =</span> <span class="st">"green"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb51-11"><a href="#cb51-11" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(modelo_gaussian, <span class="at">col =</span> <span class="st">"purple"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb51-12"><a href="#cb51-12" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(modelo_spherical, <span class="at">col =</span> <span class="st">"orange"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb51-13"><a href="#cb51-13" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(modelo_circular, <span class="at">col =</span> <span class="st">"brown"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb51-14"><a href="#cb51-14" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(modelo_cubic, <span class="at">col =</span> <span class="st">"pink"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb51-15"><a href="#cb51-15" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(modelo_wave, <span class="at">col =</span> <span class="st">"cyan"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb51-16"><a href="#cb51-16" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(modelo_powered, <span class="at">col =</span> <span class="st">"darkgreen"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb51-17"><a href="#cb51-17" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(modelo_cauchy, <span class="at">col =</span> <span class="st">"darkblue"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb51-18"><a href="#cb51-18" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(modelo_gneiting, <span class="at">col =</span> <span class="st">"black"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span>
<span id="cb51-19"><a href="#cb51-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb51-20"><a href="#cb51-20" aria-hidden="true" tabindex="-1"></a><span class="co"># Legendas</span></span>
<span id="cb51-21"><a href="#cb51-21" aria-hidden="true" tabindex="-1"></a><span class="fu">legend</span>(<span class="st">"bottomright"</span>,</span>
<span id="cb51-22"><a href="#cb51-22" aria-hidden="true" tabindex="-1"></a>       <span class="at">legend =</span> <span class="fu">c</span>(<span class="st">"Matern"</span>, <span class="st">"Exponential"</span>, <span class="st">"Gaussian"</span>, <span class="st">"Spherical"</span>,</span>
<span id="cb51-23"><a href="#cb51-23" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Circular"</span>, <span class="st">"Cubic"</span>, <span class="st">"Wave"</span>,</span>
<span id="cb51-24"><a href="#cb51-24" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Powered Exponential"</span>, <span class="st">"Cauchy"</span>, <span class="st">"Gneiting"</span>),</span>
<span id="cb51-25"><a href="#cb51-25" aria-hidden="true" tabindex="-1"></a>       <span class="at">col =</span> <span class="fu">c</span>(<span class="st">"red"</span>, <span class="st">"green"</span>, <span class="st">"purple"</span>, <span class="st">"orange"</span>,</span>
<span id="cb51-26"><a href="#cb51-26" aria-hidden="true" tabindex="-1"></a>               <span class="st">"brown"</span>, <span class="st">"pink"</span>, <span class="st">"cyan"</span>,</span>
<span id="cb51-27"><a href="#cb51-27" aria-hidden="true" tabindex="-1"></a>               <span class="st">"darkgreen"</span>, <span class="st">"darkblue"</span>, <span class="st">"black"</span>),</span>
<span id="cb51-28"><a href="#cb51-28" aria-hidden="true" tabindex="-1"></a>       <span class="at">lwd =</span> <span class="fu">rep</span>(<span class="dv">2</span>, <span class="dv">10</span>),</span>
<span id="cb51-29"><a href="#cb51-29" aria-hidden="true" tabindex="-1"></a>       <span class="at">cex =</span> <span class="fl">0.8</span>,</span>
<span id="cb51-30"><a href="#cb51-30" aria-hidden="true" tabindex="-1"></a>       <span class="at">bty =</span> <span class="st">"n"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/semivariograma%20com%20modelos-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Comparamos os valores da função objetivo dos modelos ajustados. O menor valor indica melhor ajuste ao semivariograma empírico.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb52"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1" aria-hidden="true" tabindex="-1"></a><span class="fu">sort</span>(<span class="fu">c</span>(</span>
<span id="cb52-2"><a href="#cb52-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">matern       =</span> modelo_matern<span class="sc">$</span>value,</span>
<span id="cb52-3"><a href="#cb52-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">exponential  =</span> modelo_exponential<span class="sc">$</span>value,</span>
<span id="cb52-4"><a href="#cb52-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">gaussian     =</span> modelo_gaussian<span class="sc">$</span>value,</span>
<span id="cb52-5"><a href="#cb52-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">spherical    =</span> modelo_spherical<span class="sc">$</span>value,</span>
<span id="cb52-6"><a href="#cb52-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">circular     =</span> modelo_circular<span class="sc">$</span>value,</span>
<span id="cb52-7"><a href="#cb52-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">cubic        =</span> modelo_cubic<span class="sc">$</span>value,</span>
<span id="cb52-8"><a href="#cb52-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">wave         =</span> modelo_wave<span class="sc">$</span>value,</span>
<span id="cb52-9"><a href="#cb52-9" aria-hidden="true" tabindex="-1"></a>  <span class="at">powered      =</span> modelo_powered<span class="sc">$</span>value,</span>
<span id="cb52-10"><a href="#cb52-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">cauchy       =</span> modelo_cauchy<span class="sc">$</span>value,</span>
<span id="cb52-11"><a href="#cb52-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">gneiting     =</span> modelo_gneiting<span class="sc">$</span>value</span>
<span id="cb52-12"><a href="#cb52-12" aria-hidden="true" tabindex="-1"></a>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       wave    gaussian    gneiting       cubic      cauchy    circular 
   581.8439    593.3188    594.8336    606.9397    942.7050   1291.2521 
  spherical      matern exponential     powered 
  1316.5000   1780.4502   1780.4502   3954.9445 </code></pre>
</div>
</div>
<p>Selecionamos o modelo Wave, pois apresentou o melhor desempenho segundo o critério de ajuste.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(semi, </span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">pch =</span> <span class="dv">19</span>, </span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">col =</span> <span class="st">"blue"</span>, </span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">xlab =</span> <span class="st">"Distância (km)"</span>, </span>
<span id="cb54-5"><a href="#cb54-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">ylab =</span> <span class="st">"Semivariância"</span>)</span>
<span id="cb54-6"><a href="#cb54-6" aria-hidden="true" tabindex="-1"></a><span class="fu">lines</span>(modelo_wave, <span class="at">col =</span> <span class="st">"cyan"</span>, <span class="at">lwd =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/wave-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O modelo Wave apresentou o melhor desempenho por conseguir acompanhar de forma mais fiel a estrutura de dependência espacial observada no variograma experimental. Visualmente, a curva teórica ajusta-se bem aos pontos empíricos ao longo de toda a faixa de distâncias, capturando tanto o crescimento gradual da semivariância quanto o comportamento mais suave em curtas distâncias. Em termos práticos, isso indica que o modelo consegue reproduzir a continuidade espacial do fenômeno com menor erro médio de ajuste, justificando sua seleção.</p>
</section>
<section id="krigagem-ordinária" class="level2">
<h2 class="anchored" data-anchor-id="krigagem-ordinária">Krigagem ordinária</h2>
<p>Visualizamos os pontos amostrais e construímos a grade regular onde será realizada a interpolação.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(airbnb, <span class="at">lambda=</span><span class="dv">0</span>, <span class="at">pt.div=</span><span class="st">"equal"</span>)</span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>grid_krig <span class="ot">&lt;-</span> <span class="fu">expand.grid</span>(</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">43.7</span>, <span class="sc">-</span><span class="fl">43.1</span>, <span class="at">length.out =</span> <span class="dv">300</span>),</span>
<span id="cb55-4"><a href="#cb55-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> <span class="fu">seq</span>(<span class="sc">-</span><span class="fl">23.1</span>, <span class="sc">-</span><span class="fl">22.7</span>, <span class="at">length.out =</span> <span class="dv">300</span>)</span>
<span id="cb55-5"><a href="#cb55-5" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb55-6"><a href="#cb55-6" aria-hidden="true" tabindex="-1"></a><span class="fu">points</span>(grid_krig, <span class="at">pch=</span><span class="st">"+"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/grade-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Definimos o controle da krigagem ordinária utilizando o modelo Wave ajustado e realizamos a interpolação.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Define o controle de krigagem usando o modelo 'Wave' ajustado anteriormente</span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>KC <span class="ot">&lt;-</span> <span class="fu">krige.control</span>(<span class="at">type =</span> <span class="st">"OK"</span>, <span class="at">obj.model =</span> modelo_wave)</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Realiza a krigagem ordinária nos pontos da grade</span></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>airbnb.kc <span class="ot">&lt;-</span> <span class="fu">krige.conv</span>(airbnb, <span class="at">loc =</span> grid_krig, <span class="at">krige =</span> KC)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>krige.conv: model with constant mean
krige.conv: Kriging performed using global neighbourhood </code></pre>
</div>
</div>
</section>
<section id="mapa-da-superfície-interpolada" class="level2">
<h2 class="anchored" data-anchor-id="mapa-da-superfície-interpolada">Mapa da superfície interpolada</h2>
<p>Construímos o mapa da predição obtida via krigagem.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Base da interpolação</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>df_interp <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> grid_krig[, <span class="dv">1</span>],</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> grid_krig[, <span class="dv">2</span>],</span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">value =</span> airbnb.kc<span class="sc">$</span>predict</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="co"># Base dos pontos amostrados</span></span>
<span id="cb58-9"><a href="#cb58-9" aria-hidden="true" tabindex="-1"></a>df_pts <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb58-10"><a href="#cb58-10" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> airbnb<span class="sc">$</span>coords[, <span class="dv">1</span>],</span>
<span id="cb58-11"><a href="#cb58-11" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> airbnb<span class="sc">$</span>coords[, <span class="dv">2</span>]</span>
<span id="cb58-12"><a href="#cb58-12" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb58-13"><a href="#cb58-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-14"><a href="#cb58-14" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb58-15"><a href="#cb58-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="at">data =</span> df_interp, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> value), <span class="at">interpolate =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb58-16"><a href="#cb58-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_contour</span>(<span class="at">data =</span> df_interp, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">z =</span> value), <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb58-17"><a href="#cb58-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> df_pts, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb58-18"><a href="#cb58-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">name =</span> <span class="st">"Interpolado"</span>) <span class="sc">+</span></span>
<span id="cb58-19"><a href="#cb58-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_equal</span>() <span class="sc">+</span></span>
<span id="cb58-20"><a href="#cb58-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb58-21"><a href="#cb58-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb58-22"><a href="#cb58-22" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Longitude"</span>,</span>
<span id="cb58-23"><a href="#cb58-23" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Latitude"</span></span>
<span id="cb58-24"><a href="#cb58-24" aria-hidden="true" tabindex="-1"></a>  ); p1</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/interpolação-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O mapa interpolado revela um padrão espacial bem definido, com valores mais elevados concentrados na porção sudeste da área de estudo, enquanto as menores estimativas aparecem no setor noroeste. Observa-se que a maior densidade de pontos amostrais coincide justamente com a faixa litorânea, onde se localizam as praias, indicando maior concentração do fenômeno nessas áreas. Esse adensamento sugere uma relação direta com a atratividade turística e a dinâmica costeira, que tendem a intensificar a presença e a variabilidade do atributo analisado. A superfície suavizada acompanha essa tendência, evidenciando um gradiente espacial consistente e reforçando a existência de dependência espacial capturada pelo modelo.</p>
</section>
<section id="mapa-da-incerteza" class="level2">
<h2 class="anchored" data-anchor-id="mapa-da-incerteza">Mapa da incerteza</h2>
<p>Construímos o mapa da raiz da variância da krigagem, representando a incerteza espacial das estimativas.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Imagem da variância da krigagem (incerteza)</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Criar um data frame para a variância da krigagem</span></span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>df_var <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(</span>
<span id="cb59-4"><a href="#cb59-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">x =</span> grid_krig[, <span class="dv">1</span>],</span>
<span id="cb59-5"><a href="#cb59-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">y =</span> grid_krig[, <span class="dv">2</span>],</span>
<span id="cb59-6"><a href="#cb59-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">variance =</span> <span class="fu">sqrt</span>(airbnb.kc<span class="sc">$</span>krige.var)  <span class="co"># Raiz quadrada da variância</span></span>
<span id="cb59-7"><a href="#cb59-7" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb59-8"><a href="#cb59-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-9"><a href="#cb59-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb59-10"><a href="#cb59-10" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb59-11"><a href="#cb59-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_raster</span>(<span class="at">data =</span> df_var, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y, <span class="at">fill =</span> variance), <span class="at">interpolate =</span> <span class="cn">TRUE</span>) <span class="sc">+</span></span>
<span id="cb59-12"><a href="#cb59-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>(<span class="at">data =</span> df_pts, <span class="fu">aes</span>(<span class="at">x =</span> x, <span class="at">y =</span> y), <span class="at">color =</span> <span class="st">"red"</span>, <span class="at">size =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb59-13"><a href="#cb59-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">name =</span> <span class="st">"Variância"</span>) <span class="sc">+</span></span>
<span id="cb59-14"><a href="#cb59-14" aria-hidden="true" tabindex="-1"></a>  <span class="fu">coord_equal</span>() <span class="sc">+</span></span>
<span id="cb59-15"><a href="#cb59-15" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_minimal</span>() <span class="sc">+</span></span>
<span id="cb59-16"><a href="#cb59-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">labs</span>(</span>
<span id="cb59-17"><a href="#cb59-17" aria-hidden="true" tabindex="-1"></a>    <span class="at">x =</span> <span class="st">"Longitude"</span>,</span>
<span id="cb59-18"><a href="#cb59-18" aria-hidden="true" tabindex="-1"></a>    <span class="at">y =</span> <span class="st">"Latitude"</span></span>
<span id="cb59-19"><a href="#cb59-19" aria-hidden="true" tabindex="-1"></a>  ); p2</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/incerteza-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>O mapa de variância representa a incerteza associada às estimativas interpoladas. Observa-se que as menores variâncias concentram-se na região onde há maior densidade de pontos amostrais, especialmente ao longo da faixa litorânea, onde estão as praias. Isso é esperado em krigagem: quanto mais próximos e numerosos os dados observados, menor a incerteza da predição.</p>
</section>
<section id="validação-cruzada" class="level2">
<h2 class="anchored" data-anchor-id="validação-cruzada">Validação cruzada</h2>
<p>Realizamos validação cruzada leave-one-out para avaliar o desempenho preditivo do modelo Wave.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a>vcwave <span class="ot">&lt;-</span> <span class="fu">xvalid</span>(airbnb, <span class="at">model =</span> modelo_wave)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>xvalid: number of data locations       = 1000
xvalid: number of validation locations = 1000
xvalid: performing cross-validation at location ... 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 219, 220, 221, 222, 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242, 243, 244, 245, 246, 247, 248, 249, 250, 251, 252, 253, 254, 255, 256, 257, 258, 259, 260, 261, 262, 263, 264, 265, 266, 267, 268, 269, 270, 271, 272, 273, 274, 275, 276, 277, 278, 279, 280, 281, 282, 283, 284, 285, 286, 287, 288, 289, 290, 291, 292, 293, 294, 295, 296, 297, 298, 299, 300, 301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313, 314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326, 327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339, 340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352, 353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365, 366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378, 379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391, 392, 393, 394, 395, 396, 397, 398, 399, 400, 401, 402, 403, 404, 405, 406, 407, 408, 409, 410, 411, 412, 413, 414, 415, 416, 417, 418, 419, 420, 421, 422, 423, 424, 425, 426, 427, 428, 429, 430, 431, 432, 433, 434, 435, 436, 437, 438, 439, 440, 441, 442, 443, 444, 445, 446, 447, 448, 449, 450, 451, 452, 453, 454, 455, 456, 457, 458, 459, 460, 461, 462, 463, 464, 465, 466, 467, 468, 469, 470, 471, 472, 473, 474, 475, 476, 477, 478, 479, 480, 481, 482, 483, 484, 485, 486, 487, 488, 489, 490, 491, 492, 493, 494, 495, 496, 497, 498, 499, 500, 501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513, 514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526, 527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539, 540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552, 553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565, 566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578, 579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591, 592, 593, 594, 595, 596, 597, 598, 599, 600, 601, 602, 603, 604, 605, 606, 607, 608, 609, 610, 611, 612, 613, 614, 615, 616, 617, 618, 619, 620, 621, 622, 623, 624, 625, 626, 627, 628, 629, 630, 631, 632, 633, 634, 635, 636, 637, 638, 639, 640, 641, 642, 643, 644, 645, 646, 647, 648, 649, 650, 651, 652, 653, 654, 655, 656, 657, 658, 659, 660, 661, 662, 663, 664, 665, 666, 667, 668, 669, 670, 671, 672, 673, 674, 675, 676, 677, 678, 679, 680, 681, 682, 683, 684, 685, 686, 687, 688, 689, 690, 691, 692, 693, 694, 695, 696, 697, 698, 699, 700, 701, 702, 703, 704, 705, 706, 707, 708, 709, 710, 711, 712, 713, 714, 715, 716, 717, 718, 719, 720, 721, 722, 723, 724, 725, 726, 727, 728, 729, 730, 731, 732, 733, 734, 735, 736, 737, 738, 739, 740, 741, 742, 743, 744, 745, 746, 747, 748, 749, 750, 751, 752, 753, 754, 755, 756, 757, 758, 759, 760, 761, 762, 763, 764, 765, 766, 767, 768, 769, 770, 771, 772, 773, 774, 775, 776, 777, 778, 779, 780, 781, 782, 783, 784, 785, 786, 787, 788, 789, 790, 791, 792, 793, 794, 795, 796, 797, 798, 799, 800, 801, 802, 803, 804, 805, 806, 807, 808, 809, 810, 811, 812, 813, 814, 815, 816, 817, 818, 819, 820, 821, 822, 823, 824, 825, 826, 827, 828, 829, 830, 831, 832, 833, 834, 835, 836, 837, 838, 839, 840, 841, 842, 843, 844, 845, 846, 847, 848, 849, 850, 851, 852, 853, 854, 855, 856, 857, 858, 859, 860, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 911, 912, 913, 914, 915, 916, 917, 918, 919, 920, 921, 922, 923, 924, 925, 926, 927, 928, 929, 930, 931, 932, 933, 934, 935, 936, 937, 938, 939, 940, 941, 942, 943, 944, 945, 946, 947, 948, 949, 950, 951, 952, 953, 954, 955, 956, 957, 958, 959, 960, 961, 962, 963, 964, 965, 966, 967, 968, 969, 970, 971, 972, 973, 974, 975, 976, 977, 978, 979, 980, 981, 982, 983, 984, 985, 986, 987, 988, 989, 990, 991, 992, 993, 994, 995, 996, 997, 998, 999, 1000, 
xvalid: end of cross-validation</code></pre>
</div>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(vcwave)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                  Min.     1st Qu.      Median          Mean    3rd Qu.
errors     -235.301938 -76.4808032 -11.4475505 -0.0722314923 62.8966309
std.errors   -2.362659  -0.7718737  -0.1156337 -0.0003035854  0.6328653
                 Max.         sd
errors     279.117916 100.347088
std.errors   2.812133   1.008329</code></pre>
</div>
</div>
<ul>
<li><p>Primeiro ponto crucial: o erro médio foi praticamente zero (-0,07). Isso é excelente. Significa que o modelo Wave não está consistentemente superestimando nem subestimando os valores. Em média, o erro se cancela. Isso é o que queremos.</p></li>
<li><p>Segundo ponto: os erros padronizados têm média praticamente zero (&lt;0,001) e desvio padrão de aproximadamente 1 (1.008). Isso é um sinal muito forte de que o modelo está bem calibrado. Quando o desvio padrão dos erros padronizados fica próximo de 1, significa que a variância de krigagem está coerente com a variabilidade real observada. Em outras palavras: a incerteza estimada faz sentido.</p></li>
<li><p>Olhando os extremos: há erros relativamente grandes (entre -235 e 279), o que indica presença de valores locais difíceis de prever, possivelmente outliers ou regiões com transições abruptas. Isso é comum em dados de preço de Airbnb, especialmente em áreas turísticas com heterogeneidade forte.</p></li>
<li><p>O Wave não só ajustou bem o variograma, como também se comportou adequadamente quando testado ponto a ponto.</p></li>
</ul>
<p>Analisamos graficamente os resíduos padronizados da validação. Dos quais, diagrama de dispersão dos valores observados contra os valores preditos (superior esquerdo), gráfico de probabilidade normal (central esquerdo), mapa dos redíduos positivos (+) e negativos (-) (inferior esquerdo), histograma (superior direito), diagrama de dispersão dos resíduos contra os valores preditos (central direito) e diagrama de dispersão dos resíduos versus valores observados (inferior direito).</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb64"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1" aria-hidden="true" tabindex="-1"></a><span class="fu">par</span>(<span class="at">mfcol=</span><span class="fu">c</span>(<span class="dv">3</span>,<span class="dv">2</span>))</span>
<span id="cb64-2"><a href="#cb64-2" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(vcwave, <span class="at">error=</span>F, <span class="at">std.error=</span>T)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="QMD_Modulo2_files/figure-html/graficos%20vc-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<ul>
<li><p>O diagrama de dispersão entre valores observados e preditos indica alinhamento razoável em torno da reta 1:1, sugerindo boa capacidade preditiva do modelo e ausência de viés sistemático evidente.</p></li>
<li><p>O gráfico de probabilidade normal mostra que os resíduos padronizados seguem aproximadamente a distribuição normal teórica, com pequenas discrepâncias nas extremidades, o que é esperado em dados reais.</p></li>
<li><p>O mapa dos resíduos evidencia distribuição espacial relativamente homogênea entre valores positivos e negativos, não indicando padrões espaciais remanescentes significativos, o que sugere que a estrutura de dependência espacial foi adequadamente capturada pelo modelo.</p></li>
<li><p>O histograma apresenta formato aproximadamente simétrico e centrado em zero, reforçando a adequação da padronização dos resíduos.</p></li>
<li><p>O diagrama de dispersão dos resíduos em função dos valores preditos não demonstra tendência ou padrão sistemático, indicando homocedasticidade.</p></li>
<li><p>Por fim, o gráfico dos resíduos versus valores observados mantém dispersão semelhante, sem evidências claras de estrutura não modelada.</p></li>
</ul>
</section>


<div class="no-row-height column-margin column-container"><section id="conecte-se-conosco" class="level2 margin-aside">
<h2 class="anchored" data-anchor-id="conecte-se-conosco">🌐 Conecte-se conosco</h2>
<p>👨‍💻 <strong>Daví Sousa</strong><br>
🔗 <a href="https://www.linkedin.com/in/daví-sousa-41b874180/">LinkedIn</a><br>
📚 <a href="http://lattes.cnpq.br/4206431803366749">Lattes</a></p>
<p>👩‍💻 <strong>Marcela Araujo</strong><br>
🔗 <a href="https://www.linkedin.com/in/marcela-araujoo/">LinkedIn</a><br>
📚 <a href="http://lattes.cnpq.br/8522510498165639">Lattes</a></p>
<hr>
<p>✨ Este trabalho foi desenvolvido com <a href="https://quarto.org">Quarto</a> e com ❤️</p>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>